# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: all

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt