# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: all

build:
  image: master

python:
  version: 3.7
  install:
    - requirements: REQUIREMENTS
    - requirements: ci/requirements_docs.txt
